export const Themes = {
  colors: {
    blue: '#3498DB',
    orange: '#F7DC6F',
    brightCoral: '#FFC67D',
    //black: "#00000099",
    darkGray: '#333333',
    neutralGray: '#F7F7F7',
    red: '#be0000',
    //white: "#FFFFFF",
    white: '#F9F9F9',
    textColor: '#00000099',
    green: '#8BC34A',
    backgroundColor: 'rgb(240, 240, 240)',
  },
  fonts: {
    black: 'Playfair_144pt-Black',
    blackItalic: 'Playfair_144pt-BlackItalic',
    bold: 'Playfair_144pt-Bold',
    boldItalic: 'Playfair_144pt-BoldItalic',
    extraBold: 'Playfair_144pt-ExtraBold',
    ExtraBoldItalic: 'Playfair_144pt-ExtraBoldItalic',
    italic: 'Playfair_9pt-Italic',
    medium: 'Playfair_9pt-Medium',
    mediumItalic: 'Playfair_9pt-MediumItalic',
    regular: 'Playfair_9pt-Regular',
    semiBold: 'Playfair_144pt-SemiBold',
    semiBoldItalic: 'Playfair_144pt_SemiExpanded-SemiBoldItalic',
  },
};
